name: Build extension

permissions:
  contents: read 

on:
  push:
  pull_request:
  schedule:
    - cron: '37 22 * * *'

jobs:
  builda:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
        
    steps:
    - uses: actions/checkout@v4
    - name: Set version string
      run: |
        unix_time_ns=$(($(date +%s%N)/1000000))
        echo "Unix time in nanoseconds is ${unix_time_ns}"
        extension_version="${unix_time_ns:0:4}.${unix_time_ns:4:4}.${unix_time_ns:8:4}.${unix_time_ns:12:4}"
        echo "Extension version will be ${extension_version}"
        echo "extension_version=${extension_version}" >> $GITHUB_ENV
        
    - name: Update version in update.xml and manifest.json
      run: |
        tmpfile=$(mktemp)
        jq '.address = "abcde"' extension/manifest.json > "$tmp" && mv "$tmp" extension/manifest.json
        cat extension/manifest.json
